@startuml

node archives
node index
node data
node report

index -u-> archives
data -u-> archives
report -u-> archives

node report1
node reportN
report1 -u-> report
reportN -u-> report

node data1
node dataN
data1 -u-> data
dataN -u-> data

node index1
node indexN
index1 -u-> index
indexN -u-> index

node file1
node fileN
file1 -u-> data1
fileN -u-> data1

@enduml