DROP TABLE IF EXISTS m_lock;
CREATE TABLE m_lock
(
  c_id CHAR(36) NOT NULL COMMENT '主键',
  c_md5 CHAR(32) NOT NULL COMMENT 'MD5值',
  c_key VARCHAR(255) DEFAULT NULL COMMENT '锁key',
  c_create BIGINT DEFAULT 0 COMMENT '创建时间',
  c_expire BIGINT DEFAULT 0 COMMENT '过期时间',
  c_index BIGINT AUTO_INCREMENT NOT NULL COMMENT '序号',

  PRIMARY KEY pk(c_id) USING HASH,
  KEY k_md5(c_md5) USING HASH,
  UNIQUE KEY uk_index(c_index)
) ENGINE=Memory AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
