DROP TABLE IF EXISTS t_user_crosier;
CREATE TABLE t_user_crosier
(
  c_id CHAR(36) NOT NULL COMMENT '主键',
  c_grade INT DEFAULT 0 COMMENT '等级',
  c_path VARCHAR(255) DEFAULT NULL COMMENT '路径',

  PRIMARY KEY pk(c_id) USING HASH
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
