DROP TABLE IF EXISTS t_google;
CREATE TABLE t_google
(
  c_id CHAR(36) NOT NULL COMMENT '主键',
  c_key VARCHAR(255) NOT NULL COMMENT '引用key',
  c_name VARCHAR(255) DEFAULT NULL COMMENT '名称',
  c_client_id VARCHAR(255) NOT NULL COMMENT '客户端ID',

  PRIMARY KEY pk(c_id) USING HASH,
  UNIQUE KEY uk_key(c_key) USING HASH,
  UNIQUE KEY uk_client_id(c_client_id) USING HASH
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
