DROP TABLE IF EXISTS t_alipay;
CREATE TABLE t_alipay
(
  c_id CHAR(36) NOT NULL COMMENT '主键',
  c_key VARCHAR(255) NOT NULL COMMENT '引用key',
  c_name VARCHAR(255) DEFAULT NULL COMMENT '名称',
  c_app_id VARCHAR(255) DEFAULT NULL COMMENT 'APP ID',
  c_private_key TEXT DEFAULT NULL COMMENT '私钥',
  c_public_key TEXT DEFAULT NULL COMMENT '公钥',

  PRIMARY KEY pk(c_id) USING HASH,
  UNIQUE KEY uk_key(c_key) USING HASH
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
