@startuml

[base] <-u- [gps]
[base] <-u- [classify]
[base] <-u- [comment]
[base] <-u- [doc]
[base] <-u- [user]
[base] <-u- [friend]
[base] <-u- [group]
[base] <-u- [message]
[base] <-- [snapshot]
[base] <-- [last]
[base] <-- [address]
[base] <-- [account]
[base] <-- [archives]
[test]

@enduml