@startuml

[base] <-- [gps]
[base] <-- [classify]
[base] <-- [comment]
[base] <-- [doc]
[base] <-- [user]
[base] <-- [friend]
[base] <-- [group]
[base] <-- [message]
[base] <-- [archives]
[test]

@enduml