DROP TABLE IF EXISTS t_form;
CREATE TABLE t_form
(
  c_id CHAR(36) NOT NULL COMMENT '主键',
  c_name VARCHAR(255) DEFAULT NULL COMMENT '名称',
  c_time VARCHAR(255) DEFAULT NULL COMMENT '时间轴',
  c_total INT DEFAULT 0 COMMENT '字段数',
  c_change INT DEFAULT 0 COMMENT '修改数',
  c_state INT DEFAULT 0 COMMENT '状态：0-进行中；1-已完成；2-已失效',
  c_create DATETIME DEFAULT NULL COMMENT '创建时间',
  c_modify DATETIME DEFAULT NULL COMMENT '修改时间',

  PRIMARY KEY pk(c_id) USING HASH
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
