DROP TABLE IF EXISTS t_dbtool_schema;
CREATE TABLE t_dbtool_schema
(
  c_id CHAR(36) NOT NULL COMMENT '主键',
  c_sort INT DEFAULT 0 COMMENT '显示顺序',
  c_group CHAR(36) DEFAULT NULL COMMENT '分组ID',
  c_key VARCHAR(255) DEFAULT NULL COMMENT '引用KEY',
  c_type VARCHAR(255) DEFAULT NULL COMMENT '类型',
  c_ip VARCHAR(255) DEFAULT NULL COMMENT 'IP地址',
  c_name VARCHAR(255) DEFAULT NULL COMMENT '名称',
  c_username VARCHAR(255) DEFAULT NULL COMMENT '用户名',
  c_password VARCHAR(255) DEFAULT NULL COMMENT '密码',
  c_memo VARCHAR(255) DEFAULT NULL COMMENT '备注',
  c_tables INT DEFAULT 0 COMMENT '表数量',

  PRIMARY KEY pk(c_id) USING HASH
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
