DROP TABLE IF EXISTS t_editor_download;
CREATE TABLE t_editor_download
(
  c_id CHAR(36) NOT NULL COMMENT '主键',
  c_user CHAR(36) NOT NULL COMMENT '用户',
  c_editor CHAR(36) DEFAULT NULL COMMENT '编辑器',
  c_type VARCHAR(255) DEFAULT NULL COMMENT '类型',
  c_uri VARCHAR(255) DEFAULT NULL COMMENT '源URI',
  c_temporary VARCHAR(255) DEFAULT NULL COMMENT '临时URI',
  c_time DATETIME DEFAULT NULL COMMENT '时间',

  PRIMARY KEY pk(c_id) USING HASH,
  KEY k_time_user(c_time,c_user) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
